### ISSUE TITLE
Disable file logging?

### ISSUE THREAD

**Issue by subnetz** [timepp/enhanced-deno-log#1]
Hi, I want to disable file logging, but even when I do  

```js
log.setConfig({ enabledLevels: [] }, 'file');
```  

it still creates the `./logs/` folder and an empty log file.

**Comment by timepp** [comment]
Hey, yeah it's previously designed to always create a file. 
I have changed the behavior to lazy creation of file log, so your code should now work well in version 0.4.1:
https://jsr.io/@timepp/enhanced-deno-log@0.4.1
